services:
  - type: web
    name: fulcrum-cli-backend
    env: node
    plan: free
    nodeVersion: 18
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /run-command
    autoDeploy: true
